services:
  hma-marimo:
    build: .
    image: hma-marimo-hma-marimo:latest
    container_name: hma-marimo
    restart: unless-stopped
    environment:
      - HMA_DB_URL=${HMA_DB_URL}
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - traefik.http.routers.hma-marimo.rule=Host(`gestion.hma.business`)
      - traefik.http.routers.hma-marimo.entrypoints=https
      - traefik.http.routers.hma-marimo.tls=true
      - traefik.http.routers.hma-marimo.tls.certresolver=letsencrypt
      - traefik.http.services.hma-marimo.loadbalancer.server.port=8080

networks:
  coolify:
    external: true
